### ISSUE TITLE
Get refresh token from client id and secret

### ISSUE THREAD

**Issue by BenBanerjeeRichards** [BenBanerjeeRichards/Spotify-history-downloader#3]
#1

**Comment by ethanopp** [comment]
Any chance you were able to find this script? Working on a fork for mariadb and looking to leverage if its already built :)

**Comment by BenBanerjeeRichards** [comment]
The code is pretty bad but it's at [https://github.com/BenBanerjeeRichards/Spotify-history-downloader/blob/master/get_token.py](https://github.com/BenBanerjeeRichards/Spotify-history-downloader/blob/master/get_token.py). Just a standalone script but should be able to build something off it.

The mariadb sounds like a great idea, mongodb was definitely a mistake for this project. Let me know if you have any questions. If you're just looking at storing the basic history for now then you can ignore 90% of the code in this repo, everything is just in main.py.
